// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDotnnMnCv7cF8qSe0kC9qhCVRx4vwznP4',
    appId: '1:390562657101:web:3e0d9a9fb2ebe0412efd04',
    messagingSenderId: '390562657101',
    projectId: 'besafeapp-560e0',
    authDomain: 'besafeapp-560e0.firebaseapp.com',
    storageBucket: 'besafeapp-560e0.firebasestorage.app',
    measurementId: 'G-TYZ7ZRYN5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0j87M7k90XOMNsUqArkupe1yVREJUr5M',
    appId: '1:390562657101:android:ea3db32010f8def22efd04',
    messagingSenderId: '390562657101',
    projectId: 'besafeapp-560e0',
    storageBucket: 'besafeapp-560e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkN7b2fFebZO0QlEhvTHeVG21R3-fLQCw',
    appId: '1:390562657101:ios:0ba28cb7a292f3342efd04',
    messagingSenderId: '390562657101',
    projectId: 'besafeapp-560e0',
    storageBucket: 'besafeapp-560e0.firebasestorage.app',
    iosBundleId: 'com.example.graduationApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkN7b2fFebZO0QlEhvTHeVG21R3-fLQCw',
    appId: '1:390562657101:ios:0ba28cb7a292f3342efd04',
    messagingSenderId: '390562657101',
    projectId: 'besafeapp-560e0',
    storageBucket: 'besafeapp-560e0.firebasestorage.app',
    iosBundleId: 'com.example.graduationApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDotnnMnCv7cF8qSe0kC9qhCVRx4vwznP4',
    appId: '1:390562657101:web:cc067270a042d7252efd04',
    messagingSenderId: '390562657101',
    projectId: 'besafeapp-560e0',
    authDomain: 'besafeapp-560e0.firebaseapp.com',
    storageBucket: 'besafeapp-560e0.firebasestorage.app',
    measurementId: 'G-YTQF6WP2Q1',
  );
}
